// Test routes with REST client vscode extension.
@FirebaseURL = <Your Firebase DB URL>

###

GET {{FirebaseURL}}/test.json 
Content-Type: application/json

###
POST {{FirebaseURL}}/test.json
Content-Type: application/json

{
    "title": "Hello",
    "message": "test"
}

###

// Authenctication

@signInApiKey = <Your DB auth api key>

@signUp = https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=

// Registration request
POST {{signUp}}{{signInApiKey}}
Content-Type: application/json

{
    "email": "abc123@email.com",
    "password": "abc123",
    "returnSecureToken": true
}

@idToken = <Your token after you registered>

@signIn = https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=

###
// Login request
POST {{signIn}}{{signInApiKey}}
Content-Type: application/json

{
    "email": "abc123@email.com",
    "password": "abc123",
    "returnSecureToken": true
}

###
// Authorized user
GET {{FirebaseURL}}.json?auth={{idToken}}

###
// Unauthorized user

GET {{FirebaseURL}}.json